apiVersion: v1
kind: Service
metadata:
  name: carrinhocompra-svc
  labels:
    app: carrinhocompra
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 3000
  selector:
    app: carrinhocompra
